baseURL: https://cosma.graphlab.fr/
languageCode: fr-FR
title: Cosma
theme: xmin
outputs:
  home:
  - HTML
  - RSS
  section:
  - HTML
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"
params:
  tagline:
    primary: de la fiche au graphe...
    secondary: Un outil de visualisation et de partage pour les travailleurs de la connaissance
  description:  "Cosma est un logiciel de visualisation de graphe documentaire. Il permet de représenter des fichiers Markdown interreliés sous la forme d’un réseau interactif dans un navigateur web."
  keywords:
    - graphe
    - document
    - donnée
    - corpus
    - visualisation
    - publication
    - web
    - Markdown
    - Zettelkasten
  authors:
    - Arthur Perret
    - Guillaume Brioudes

menu:
  main:
    - name: Télécharger
      url: "telecharger/"
      weight: 1
    - name: Blog
      url: "blog/"
      weight: 2
    - name: Documentation
      url: "docs/"
      weight: 3
    - name: FAQ
      url: "faq/"
      weight: 4
    - name: À propos
      url: "a-propos/"
      weight: 5
  footer:
    - name: Flux RSS
      url: "https://cosma.graphlab.fr/feed.xml"
      weight: 1
    - name: Dépôt GitHub
      url: "https://github.com/graphlab-fr/cosma"
      weight: 2
    - name: Licence
      url: "https://github.com/graphlab-fr/cosma/blob/master/LICENSE"
      weight: 3
    - name: Releases
      url: "https://github.com/graphlab-fr/cosma/releases"
      weight: 4
    - name: Issues
      url: "https://github.com/graphlab-fr/cosma/issues"
      weight: 5

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 2
    ordered: false