baseURL: https://cosma.netlify.app/
languageCode: fr-FR
title: Cosma
theme: xmin

params:
  tagline:
    primary: de la fiche au graphe...
    secondary: Un outil de visualisation et de partage pour les travailleurs de la connaissance
  description:  "Cosma est un logiciel de visualisation de graphe documentaire. Il permet d’enregistrer et représenter des fichiers Markdown interreliés sous la forme d’un réseau interactif dans un navigateur web."
  keywords:
    - graphe
    - document
    - donnée
    - corpus
    - visualisation
    - publication
    - web
    - Markdown
    - Zettelkasten
  authors:
    - Arthur Perret
    - Guillaume Brioudes

menu:
  main:
    - name: Télécharger
      url: "telecharger/"
      weight: 1
    - name: Blog
      url: "blog/"
      weight: 2
    - name: Documentation
      url: "https://graphlab-fr.github.io/cosma/fr.html"
      weight: 3
    - name: À propos
      url: "a-propos/"
      weight: 4
  footer:
    - name: FAQ
      url: "https://graphlab-fr.github.io/cosma/fr.html#faq"
      weight: 1
    - name: GitHub
      url: "https://github.com/graphlab-fr/cosma"
      weight: 2
    - name: Licence
      url: "https://github.com/graphlab-fr/cosma/blob/master/LICENSE"
      weight: 3
    - name: Releases
      url: "https://github.com/graphlab-fr/cosma/releases"
      weight: 4
    - name: Issues
      url: "https://github.com/graphlab-fr/cosma/releases"
      weight: 5
    - name: Contact
      url: "contact/"
      weight: 6
